name: CWO SPC Daily Outlook Emailer

on:
  schedule:
    # 1315Z = after SPC morning outlooks are all issued
    - cron: "15 13 * * *"
    # 2015Z = after SPC afternoon update
    - cron: "15 20 * * *"
  workflow_dispatch:

jobs:
  send-outlook-email:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run CWO SPC Emailer
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          TO_EMAIL:   ${{ secrets.TO_EMAIL }}
        run: python spc_emailer.py
